sudo: false
language: fortran

compiler: gfortran-6
os: linux
env: TESTID='icar_linux'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libfftw3-dev
      - gfortran-6

before_install:
  - source ci/icar_install_utils
  - icar_before_install
install:
   - icar_install
script:
  - icar_script
after_success:
  - icar_after_success
after_failure:
  - icar_after_failure
