site_name: ICAR
pages:
- Home: index.md
- Compiling: compiling.md
- Running: running.md
- Developing: developing.md
- Errors: errors.md
theme: readthedocs
google_analytics: ['UA-108421993-4', 'icar.readthedocs.org']
