name: ICAR Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run_fortran:
    env: TESTID='icar_linux'
    runs-on: ubuntu-20.04
    # runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: bash .github/scripts/icar_install_utils.sh icar_dependencies
      - name: Install
        run: bash .github/scripts/icar_install_utils.sh icar_install
      - name: Run script
        run: bash .github/scripts/icar_install_utils.sh icar_script
